#!/bin/bash
# WF 2022-05-02
# start Google Spreadssheet Import
log="/tmp/gsimport.log"
export PYTHONPATH="."
app="wd/gsimport.py"
appproc=$(pgrep -f $app)
if [ $? -eq 0 ]
then
  echo "killing running $app"
  kill -9 $appproc
fi
echo "starting $app"
nohup python3 $app --url $1 --sheets $2 $3 $4 >$log 2>&1 &
delay=6
echo "waiting $delay secs ..."
sleep $delay
echo "opening justpy browser"
open http://localhost:8000
echo "log content at $log:"
head $log
tail -f $log
